name: .NET API CI, Test and Deploy

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - name: Hent kildekode
        uses: actions/checkout@v4

      - name: Opsæt .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Byg koden
        run: dotnet build --configuration Release --no-restore

      - name: Kør Unit Tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Publish
        run: dotnet publish --configuration Release --no-build -o "${{ env.DOTNET_ROOT }}/myapp"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.DOTNET_ROOT }}/myapp


  deploy:
    runs-on: windows-latest
    needs: build-and-test

    # Deploy kun ved push til master eller manuel kørsel
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/master')

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C8C70776E4224005939D9BE363236961 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_962B8D0C412E4AD19C7E0EB04701F396 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FD25F7AE86A04124A1BD95E41C71F018 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AktieHandel'
          slot-name: 'Production'
          package: .